// an array of all BJC division strings
const divisions = [
    'Anesthesiology',
    'Medicine',
    'Neurology',
    'Neuroscience',
    'Neurosurgery',
    'Obstetrics and Gynecology',
    'Ophthalmology and Visual Sciences',
    'Orthopaedic Surgery',
    'Otolaryngology',
    'Pathology and Immunology',
    'Pediatrics',
    'Radiation Oncology',
    'Radiology',
    'Surgury',
    'Division of Cardiothoracic Surgery',
    'Division of General Surgery',
    'Section of Acute and Critical Care Surgery',
    'Section of Colon and Rectal Surgery',
    'Section of Hepatobiliary-Pancreatic & GI Surgery',
    'Section of Minimally Invasive Surgery',
    'Section of Surgical Oncology',
    'Section of Transplant Surgery',
    'Section of Vascular Surgery',
    'Division of Pediatric Surgery',
    'Division of Plastic and Reconstructive Surgery',
    'Division of Public Health Sciences',
    'Division of Urologic Surgery',
    'Allergy and Immunology',
    'Bioorganic Chemistry and Molecular Pharmacology',
    'Bone and Mineral Diseases',
    'Cardiology/Cardiovascular Diseases',
    'Dermatology',
    'Endocrinology/Metabolism/Lipid Research',
    'Gastroenterology',
    'General Medical Sciences',
    'General Medicine',
    'Geriatrics and Nutritional Sciences',
    'Hematology',
    'Hospital Medicine',
    'Infectious Diseases',
    'Nephrology',
    'Oncology',
    'Palliative Medicine',
    'Pulmonary and Critical Care Medicine',
    'Rheumatology'
]